<?php

namespace Container79UNsS1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X0DbDZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X0DbD_z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X0DbD_z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'purchaseRepository' => ['privates', 'App\\Repository\\PurchaseRepository', 'getPurchaseRepositoryService', true],
            'stripeService' => ['privates', 'App\\Stripe\\StripeService', 'getStripeServiceService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'purchaseRepository' => 'App\\Repository\\PurchaseRepository',
            'stripeService' => 'App\\Stripe\\StripeService',
        ]);
    }
}
