<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container79UNsS1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container79UNsS1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container79UNsS1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container79UNsS1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container79UNsS1\App_KernelDevDebugContainer([
    'container.build_hash' => '79UNsS1',
    'container.build_id' => 'b9c80d36',
    'container.build_time' => 1613217778,
], __DIR__.\DIRECTORY_SEPARATOR.'Container79UNsS1');
